dbt:
  outputs:
    dev:
      account: WUILKZT-JS95803
      database: airbnb
      password: Trovao@852123
      role: accountadmin
      schema: dev
      threads: 1
      type: snowflake
      user: movmarcos
      warehouse: compute_wh
  target: dev

elementary:
  outputs:
    dev:
      account: WUILKZT-JS95803
      database: airbnb
      password: Trovao@852123
      role: accountadmin
      schema: dev_elementary
      threads: 1
      type: snowflake
      user: movmarcos
      warehouse: compute_wh
  target: dev